In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
traindf = pd.read_csv("training_set.csv")

In [3]:
traindf.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Approval_Rate
count,612.000000,613.000000,592.000000,600.00000,564.000000,614.000000
mean,5405.540850,1620.888940,146.412162,342.00000,0.842199,49.905375
std,6118.914057,2928.624748,85.587325,65.12041,0.364878,29.826676
min,150.000000,0.000000,9.000000,12.00000,0.000000,0.510000
25%,2875.750000,0.000000,100.000000,360.00000,1.000000,23.810000
50%,3806.000000,1167.000000,128.000000,360.00000,1.000000,51.170000
75%,5803.750000,2302.000000,168.000000,360.00000,1.000000,76.005000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000,99.970000

In [4]:
traindf.dtypes

Loan_ID                  str
Gender                   str
Married                  str
Dependents               str
Education                str
Self_Employed            str
ApplicantIncome      float64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
property_Area            str
Loan_Status              str
Approval_Rate        float64
dtype: object

In [5]:
traindf

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,property_Area,Loan_Status,Approval_Rate
0,LP001002,Male,No,0,Graduate,No,5849.0,0.0,NaN,360.0,1.0,Urban,Y,37.45
1,LP001003,Male,Yes,1,Graduate,No,NaN,1508.0,128.0,360.0,1.0,Rural,N,95.07
2,LP001005,Male,Yes,0,Graduate,Yes,3000.0,0.0,66.0,360.0,1.0,Urban,Y,73.20
3,LP001006,Male,Yes,0,Not Graduate,No,2583.0,2358.0,120.0,360.0,1.0,Urban,Y,59.87
4,LP001008,Male,No,0,Graduate,No,6000.0,0.0,141.0,360.0,1.0,Urban,Y,15.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900.0,0.0,71.0,360.0,1.0,Rural,Y,69.04
610,LP002979,Male,Yes,3+,Graduate,No,4106.0,0.0,40.0,180.0,1.0,Rural,Y,3.93
611,LP002983,Male,Yes,1,Graduate,No,8072.0,240.0,253.0,360.0,1.0,Urban,Y,79.94
612,LP002984,Male,Yes,2,Graduate,No,7583.0,0.0,187.0,360.0,1.0,Urban,Y,62.79
613,LP002990,Female,No,0,Graduate,Yes,4583.0,0.0,133.0,360.0,0.0,Semiurban,N,8.18

In [6]:
traindf.drop_duplicates(inplace=True)

In [7]:
traindf

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,property_Area,Loan_Status,Approval_Rate
0,LP001002,Male,No,0,Graduate,No,5849.0,0.0,NaN,360.0,1.0,Urban,Y,37.45
1,LP001003,Male,Yes,1,Graduate,No,NaN,1508.0,128.0,360.0,1.0,Rural,N,95.07
2,LP001005,Male,Yes,0,Graduate,Yes,3000.0,0.0,66.0,360.0,1.0,Urban,Y,73.20
3,LP001006,Male,Yes,0,Not Graduate,No,2583.0,2358.0,120.0,360.0,1.0,Urban,Y,59.87
4,LP001008,Male,No,0,Graduate,No,6000.0,0.0,141.0,360.0,1.0,Urban,Y,15.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900.0,0.0,71.0,360.0,1.0,Rural,Y,69.04
610,LP002979,Male,Yes,3+,Graduate,No,4106.0,0.0,40.0,180.0,1.0,Rural,Y,3.93
611,LP002983,Male,Yes,1,Graduate,No,8072.0,240.0,253.0,360.0,1.0,Urban,Y,79.94
612,LP002984,Male,Yes,2,Graduate,No,7583.0,0.0,187.0,360.0,1.0,Urban,Y,62.79
613,LP002990,Female,No,0,Graduate,Yes,4583.0,0.0,133.0,360.0,0.0,Semiurban,N,8.18

In [8]:
traindf.drop('Loan_ID', axis = 1 , inplace =True)

In [9]:
traindf

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,property_Area,Loan_Status,Approval_Rate
0,Male,No,0,Graduate,No,5849.0,0.0,NaN,360.0,1.0,Urban,Y,37.45
1,Male,Yes,1,Graduate,No,NaN,1508.0,128.0,360.0,1.0,Rural,N,95.07
2,Male,Yes,0,Graduate,Yes,3000.0,0.0,66.0,360.0,1.0,Urban,Y,73.20
3,Male,Yes,0,Not Graduate,No,2583.0,2358.0,120.0,360.0,1.0,Urban,Y,59.87
4,Male,No,0,Graduate,No,6000.0,0.0,141.0,360.0,1.0,Urban,Y,15.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,2900.0,0.0,71.0,360.0,1.0,Rural,Y,69.04
610,Male,Yes,3+,Graduate,No,4106.0,0.0,40.0,180.0,1.0,Rural,Y,3.93
611,Male,Yes,1,Graduate,No,8072.0,240.0,253.0,360.0,1.0,Urban,Y,79.94
612,Male,Yes,2,Graduate,No,7583.0,0.0,187.0,360.0,1.0,Urban,Y,62.79
613,Female,No,0,Graduate,Yes,4583.0,0.0,133.0,360.0,0.0,Semiurban,N,8.18

In [10]:
traindf.isnull().sum()

Gender               15
Married               3
Dependents           15
Education             1
Self_Employed        32
ApplicantIncome       2
CoapplicantIncome     1
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
property_Area         0
Loan_Status           0
Approval_Rate         0
dtype: int64

In [11]:
traindf['Gender'].unique()

<StringArray>
['Male', nan, 'Female']
Length: 3, dtype: str

In [12]:
traindf['Gender'] = traindf['Gender'].fillna('Missing')

In [13]:
traindf['Gender'] = traindf['Gender'].astype('category')

In [14]:
traindf.isnull().sum()

Gender                0
Married               3
Dependents           15
Education             1
Self_Employed        32
ApplicantIncome       2
CoapplicantIncome     1
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
property_Area         0
Loan_Status           0
Approval_Rate         0
dtype: int64

In [15]:
traindf.dtypes
#married -cat , dependents -cat  , education - bool ? , self employed -bool ?

Gender               category
Married                   str
Dependents                str
Education                 str
Self_Employed             str
ApplicantIncome       float64
CoapplicantIncome     float64
LoanAmount            float64
Loan_Amount_Term      float64
Credit_History        float64
property_Area             str
Loan_Status               str
Approval_Rate         float64
dtype: object

In [16]:
traindf['Married'] = traindf['Married'].fillna('Missing')
traindf['Married'] = traindf['Married'].astype('category')

In [17]:
traindf.isnull().sum()

Gender                0
Married               0
Dependents           15
Education             1
Self_Employed        32
ApplicantIncome       2
CoapplicantIncome     1
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
property_Area         0
Loan_Status           0
Approval_Rate         0
dtype: int64

In [18]:
traindf['Dependents'] = traindf['Dependents'].fillna('Missing')
traindf['Dependents'] = traindf['Dependents'].astype('category')

In [19]:
traindf.isnull().sum()

Gender                0
Married               0
Dependents            0
Education             1
Self_Employed        32
ApplicantIncome       2
CoapplicantIncome     1
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
property_Area         0
Loan_Status           0
Approval_Rate         0
dtype: int64

In [20]:
traindf['Education'] = traindf['Dependents'].fillna(traindf['Dependents'].mode()[0])

In [21]:
traindf['Education'] = traindf['Education'].astype('bool')

In [22]:
traindf.isnull().sum()

Gender                0
Married               0
Dependents            0
Education             0
Self_Employed        32
ApplicantIncome       2
CoapplicantIncome     1
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
property_Area         0
Loan_Status           0
Approval_Rate         0
dtype: int64

In [23]:
traindf['Self_Employed'] = traindf['Self_Employed'].fillna('Missing')
traindf['Self_Employed'] = traindf['Self_Employed'].astype('category')

In [24]:
traindf.isnull().sum()

Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       2
CoapplicantIncome     1
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
property_Area         0
Loan_Status           0
Approval_Rate         0
dtype: int64

In [25]:
traindf.dtypes

Gender               category
Married              category
Dependents           category
Education                bool
Self_Employed        category
ApplicantIncome       float64
CoapplicantIncome     float64
LoanAmount            float64
Loan_Amount_Term      float64
Credit_History        float64
property_Area             str
Loan_Status               str
Approval_Rate         float64
dtype: object